services:
  focus-flow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: focus-flow-app
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/db/prod.db
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      # Mapping diretto della cartella per il DB SQLite
      - ./db:/app/db
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true